INSERT INTO brands (id, name) VALUES (1, 'Acura');
INSERT INTO brands (id, name) VALUES (2, 'Audi');
INSERT INTO brands (id, name) VALUES (3, 'Bentley');
INSERT INTO brands (id, name) VALUES (4, 'BMW');
INSERT INTO brands (id, name) VALUES (5, 'Buick');
INSERT INTO brands (id, name) VALUES (6, 'Cadillac');
INSERT INTO brands (id, name) VALUES (7, 'Chevrolet');
INSERT INTO brands (id, name) VALUES (8, 'Chrysler');
INSERT INTO brands (id, name) VALUES (9, 'Dodge');
INSERT INTO brands (id, name) VALUES (10, 'FAW');
INSERT INTO brands (id, name) VALUES (11, 'Ferrari');
INSERT INTO brands (id, name) VALUES (12, 'Fiat');
INSERT INTO brands (id, name) VALUES (13, 'Ford');
INSERT INTO brands (id, name) VALUES (14, 'GMC');
INSERT INTO brands (id, name) VALUES (15, 'Honda');
INSERT INTO brands (id, name) VALUES (16, 'Infiniti');
INSERT INTO brands (id, name) VALUES (17, 'Jaguar');
INSERT INTO brands (id, name) VALUES (18, 'Jeep');
INSERT INTO brands (id, name) VALUES (19, 'Lamborghini');
INSERT INTO brands (id, name) VALUES (20, 'Land Rover');
INSERT INTO brands (id, name) VALUES (21, 'Lincoln');
INSERT INTO brands (id, name) VALUES (22, 'Maserati');
INSERT INTO brands (id, name) VALUES (23, 'Mastretta');
INSERT INTO brands (id, name) VALUES (24, 'Mazda');
INSERT INTO brands (id, name) VALUES (25, 'Mercedes Benz');
INSERT INTO brands (id, name) VALUES (26, 'Mitsubishi');
INSERT INTO brands (id, name) VALUES (27, 'Nissan');
INSERT INTO brands (id, name) VALUES (28, 'Peugeot');
INSERT INTO brands (id, name) VALUES (29, 'Porsche');
INSERT INTO brands (id, name) VALUES (30, 'RAM');
INSERT INTO brands (id, name) VALUES (31, 'Renault');
INSERT INTO brands (id, name) VALUES (32, 'Rolls Royce');
INSERT INTO brands (id, name) VALUES (33, 'Seat');
INSERT INTO brands (id, name) VALUES (34, 'Smart');
INSERT INTO brands (id, name) VALUES (35, 'Subaru');
INSERT INTO brands (id, name) VALUES (36, 'Suzuki');
INSERT INTO brands (id, name) VALUES (37, 'Toyota');
INSERT INTO brands (id, name) VALUES (38, 'Volkswagen');
INSERT INTO brands (id, name) VALUES (39, 'Volvo');
INSERT INTO brands (id, name) VALUES (40, 'Alfa Romeo');
INSERT INTO brands (id, name) VALUES (41, 'Hummer');
INSERT INTO brands (id, name) VALUES (42, 'Hyundai');
INSERT INTO brands (id, name) VALUES (43, 'Isuzu');
INSERT INTO brands (id, name) VALUES (44, 'McLaren');
INSERT INTO brands (id, name) VALUES (45, 'Mercury');
INSERT INTO brands (id, name) VALUES (46, 'Cbo');
INSERT INTO brands (id, name) VALUES (47, 'Pontiac');
INSERT INTO brands (id, name) VALUES (48, 'Saab');
INSERT INTO brands (id, name) VALUES (49, 'Aston Martin');
INSERT INTO brands (id, name) VALUES (50, 'Lotus');
INSERT INTO brands (id, name) VALUES (51, 'MG');
INSERT INTO brands (id, name) VALUES (52, 'Tesla');
INSERT INTO brands (id, name) VALUES (53, 'Abarth');
INSERT INTO brands (id, name) VALUES (54, 'KIA');
INSERT INTO brands (id, name) VALUES (55, 'Mini Cooper');
INSERT INTO brands (id, name) VALUES (56, 'Baic');
INSERT INTO brands (id, name) VALUES (57, 'JAC');
INSERT INTO brands (id, name) VALUES (58, 'HINO');
INSERT INTO brands (id, name) VALUES (59, 'International');
INSERT INTO brands (id, name) VALUES (60, 'UAZ');
INSERT INTO brands (id, name) VALUES (61, 'Zacua');